{% set domainNameNormalized = values.domain | replace(r/domain:| |-/, "") %}
{% set dataProductNameNormalized = values.dataproduct.split(".")[1] | replace(r/ |-/g, "") %}
{% set dataProductMajorVersion = values.identifier.split(".")[2] %}

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  description: |
      ${{ values.description }}
spec:
  type: outputport
  lifecycle: experimental
  owner: ${{ values.developmentGroup }}
  mesh:
    fullyQualifiedName: ${{ values.fullyQualifiedName }}
    description: |
        ${{ values.description }}
    dependsOn: {% if values.dependsOn | length > 0 %}{% for i in values.dependsOn %}
      - ${{ i }}{% endfor %}{% else %}[]{% endif %}
    dataContract:
      schema: {% if values.schemaColumns | length > 0 %}{% for i in values.schemaColumns %}
        - name: ${{ i.name }}
          dataType: ${{ i.dataType }}{% if i.constraint is defined and i.constraint != '(no constraint)' %}
          constraint: ${{ i.constraint }}{% endif %}{% if i.dataLength is defined and i.dataType == 'TEXT' %}
          dataLength: ${{ i.dataLength }}{% endif %}{% if i.precision is defined and i.dataType == 'NUMBER' %}
          precision: ${{ i.precision }}{% endif %}{% if i.scale is defined and i.dataType == 'NUMBER' %}
          scale: ${{ i.scale }}{% endif %}
          tags: {% if i.businessTerms | length > 0 or i.piiCheck %}
            {% if i.businessTerms | length > 0 %}
              {% for j in i.businessTerms %}
            - tagFQN: ${{ j }}
              source: Glossary
              labelType: Manual
              state: Confirmed
              {% endfor %}
            {% endif %}
            {% if i.piiCheck %}
            - tagFQN: PII
              source: Tag
              labelType: Manual
              state: Confirmed
            {% endif %}
          {% else %}[]{% endif %}{% endfor %}{% else %}[]{% endif %}
      termsAndConditions: ${{ values.termsAndConditions }}
      SLA:
        intervalOfChange: ${{ values.intervalOfChange }}
        timeliness: ${{ values.timeliness }}
        upTime: ${{ values.upTime }}
    dataSharingAgreement:
      purpose: ${{ values.purpose }}
      billing: ${{ values.billing }}
      security: ${{ values.security }}
      intendedUsage: ${{ values.intendedUsage }}
      limitations: ${{ values.limitations }}
      lifeCycle: ${{ values.lifeCycle }}
      confidentiality: ${{ values.confidentiality }}
    tags: {% if values.tags | length > 0 %}{% for i in values.tags %}
      - tagFQN: ${{ i }}
        source: Tag
        labelType: Manual
        state: Confirmed{% endfor %}{% else %}[]{% endif %}
    specific:
      viewName: ${{ values.viewName | upper }}
      tableName: ${{ values.tableName | upper }}
      database: {% if (values.database | length) == 0 %}
        {% set finalDatabaseName = domainNameNormalized %}
        {% else %}
        {% set finalDatabaseName = values.database | replace(r/ |-/, "") %}
        {% endif %}
        ${{ finalDatabaseName | upper }}
      schema: {% if (values.schema | length) == 0 %}
        {% set finalSchemaName = dataProductNameNormalized + "_" + dataProductMajorVersion %}
        {% else %}
        {% set finalSchemaName = values.schema | replace(r/ |-/, "") %}
        {% endif %}
        ${{ finalSchemaName | upper }}