apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.identifier }}
  description: ${{ values.description | dump }}
  annotations:
    gitlab.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - outputport
    - snowflake
spec:
  type: workload
  lifecycle: experimental
  owner: ${{ values.developmentGroup | dump }}
  system: ${{ values.dataproduct | dump }}
  domain: ${{ values.domain | dump }}
  mesh:
    name: ${{ values.name | dump }}
    fullyQualifiedName: ${{ values.fullyQualifiedName | dump }}
    description: ${{ values.description | dump }}
    kind: outputport
    version: ${{ values.identifier.split(".")[2] + ".0.0" }}
    infrastructureTemplateId: ${{ values.infrastructureTemplateId }}
    useCaseTemplateId: ${{ values.useCaseTemplateId }}
    dependsOn: {% if values.dependsOn | length > 0 %}{% for i in values.dependsOn %}
      - ${{ i }}{% endfor %}{% else %}[]{% endif %}
    platform: Snowflake
    technology: Snowflake
    outputPortType: SQL
    creationDate: ${{ values.creationDate }}
    startDate: ${{ values.creationDate }}
    dataContract:
      schema:
        - name: date
          dataType: TEXT
          constraint: NO CONSTRAINT
        - name: location_key
          dataType: TEXT
          constraint: NO CONSTRAINT
        - name: new_confirmed
          dataType: NUMBER
          constraint: NO CONSTRAINT
        - name: new_deceased
          dataType: NUMBER
          constraint: NO CONSTRAINT
        - name: new_recovered
          dataType: NUMBER
          constraint: NO CONSTRAINT
        - name: new_tested
          dataType: NUMBER
          constraint: NO CONSTRAINT
        - name: cumulative_confirmed
          dataType: NUMBER
          constraint: NO CONSTRAINT
        - name: cumulative_deceased
          dataType: NUMBER
          constraint: NO CONSTRAINT
        - name: cumulative_recovered
          dataType: NUMBER
          constraint: NO CONSTRAINT
        - name: cumulative_tested
          dataType: NUMBER
          constraint: NO CONSTRAINT
    tags: []
    sampleData: {}
    semanticLinking: []
    specific:
      tableName: ${{ values.tableName }}
      database: ${{ values.database }}
      schema: ${{ values.schema }}